services:
  test:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      command: sh docker/test.sh
      volumes:
        - .:/app
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: reflex -c reflex.conf
    volumes:
      - .:/app
      - shared-data:/shared
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["./docker/wait-for-rabbit.sh", "rabbitmq", "5672", "reflex", "-c", "reflex.worker.conf"]
    volumes:
      - .:/app
      - shared-data:/shared
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # web interface : http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8
    container_name: go_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  shared-data: # share volume between services to save and read uploaded files
  mysql_data:
